---
name: cd

'on':
  push:
    branches: [master]

jobs:
  ci:
    uses: ./.github/workflows/ci.yaml
  cd:
    needs: ['ci']
    name: Continuos Delivery
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build-react
      - name: Print the final result
        run: ls -la
      - name: Archive site content
        uses: thedoctor0/zip-release@master
        with:
          filename: react.zip
      - name: Create GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.rum_number }}
          draft: false
          prerelease: false
