name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  bootstrap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.16.0
        uses: actions/setup-node@v3
        with:
          node-version: '16.16.0'
      - run: npm ci
      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: cache-${{ hashFiles('**/package-lock.json') }}

  lint:
    needs: [bootstrap]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.16.0
        uses: actions/setup-node@v3
        with:
          node-version: '16.16.0'
      - name: Restore cache
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: cache-${{ hashFiles('**/package-lock.json') }}
      - run: npm run lint
  test:
    needs: [bootstrap]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.16.0
        uses: actions/setup-node@v3
        with:
          node-version: '16.16.0'
      - name: Restore cache
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: cache-${{ hashFiles('**/package-lock.json') }}
      - run: npm run test
  build:
    needs: ['lint', 'test']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.16.0
        uses: actions/setup-node@v3
        with:
          node-version: '16.16.0'
      - name: Restore cache
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: cache-${{ hashFiles('**/package-lock.json') }}
      - run: npm run build --if-present
      - name: Cache build
        id: build
        uses: actions/cache@v3
        with:
          path: ./build
          key: build-${{ hashFiles('**/package-lock.json') }}
  artifact:
    needs: ['build']
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - name: Restore cache build
        id: build
        uses: actions/cache@v3
        with:
          path: ./build
          key: build-${{ hashFiles('**/package-lock.json') }}
      - name: Archive Build
        uses: actions/upload-artifact@v3
        with:
          name: build-react
          path: ./build
  dispatch:
    needs: ['artifact']
    uses: ./github/workflows/cd.yaml@master
